### ISSUE TITLE
Setup AWS account for NOAA Flood Inundation Modeling

### ISSUE THREAD

**Issue by echeipesh** [azavea/noaa-flood-mapping#1]
We will have to keep track of AWS costs for this work so it should be separated into its own account.

Expected activities are:
- S3 Buckets to hold and host relevant data
- AWS Batch jobs to transform data (COGify datasets)
- AWS Batch + ECR to train and run Raster Vision models
- ECS, RDS to deploy Franklin to host experiment results and index datasets
- Lambda to index updates to datasets like Sentinel 1 (maybe, under discussion)

**Comment by CloudNiner** [comment]
I started on #2 and one of the tasks there is to copy the original sen1floods11 dataset to our s3 bucket once this task is complete. As part of this issue can I get access to an AWS account user able to transfer data into S3 so I can complete #2?

**Comment by hectcastro** [comment]
- [x] Added root AWS credentials to LastPass under `Shared-Azavea Ops`
- [x] Added the account to Cloudability
- [x] Enabled CloudTrail audit logging
- [x] Created an account for @CloudNiner with access to S3
