### ISSUE TITLE
collection extent bbox incorrectly formatted

### ISSUE THREAD

**Issue by echeipesh** [azavea/noaa-flood-mapping#105]
I saw this issue in `hand` and `senfloods` catalogs but likely its an issue everywhere

The collection `extent` tag is:

```json
    "title": "HAND and the Hydraulic Property Table version 0.2.1",
    "extent": {
        "spatial": {
            "bbox": [
                -124.90220439990048,
                48.57285024335522,
                -123.0335319132177,
                52.88065372625198
            ]
        },
        "temporal": {
            "interval": [
                [
                    "2020-06-01T00:00:00Z",
                    null
                ]
            ]
        }
    }
```

Note that the `bbox` is a single list. 
Note that the spec specifies it as `[[number]]` -- likely so we could have several AOIs that are part of one collection without forcing it merge extents too eagerly (ie: item in CONUS and Item in Hawaii would not cover most of the pacific)
https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#spatial-extent-object

I encountered this error when trying to import the collection into Franklin, which resulted in failed ingest of the collection.
(This is likely actually a pystac issue)

**Comment by CloudNiner** [comment]
Yuuuuup. 🤦. [SpatialExtent](https://pystac.readthedocs.io/en/latest/api.html#pystac.SpatialExtent) takes `bboxes` as a `list[list[float]]` not just a `list[float]` so this is user error. Gonna have to check each catalog.
