### ISSUE TITLE
Deploy Public Franklin Instance to NOAA AWS Account

### ISSUE THREAD

**Issue by notthatbreezy** [azavea/noaa-flood-mapping#15]
We would like to deploy a version of Franklin deployed in the NOAA account. This should be publicly accessible (different from our internal franklin.rasterfoundry.com instance in that sense) and should not have the transactions extension enabled as a result.

I don't know what the domain should be, but since this is where we would like advertise publicly `franklin.azavea.com` may be appropriate. What do you think @echeipesh ?

**Comment by hectcastro** [comment]
Is there a possibility to use a single Franklin instance for the purposes here and RF? Trying to sort out how to best deal with https://github.com/azavea/franklin-deployment being somewhat tightly coupled with RF right now. I think we can setup a new instance of Franklin unique to the NOAA effort, but it would be better to avoid having multiple instances with distinct Terraform projects if we can avoid it.
