### ISSUE TITLE
Sen1Floods11 STAC

### ISSUE THREAD

**Issue by echeipesh** [azavea/noaa-flood-mapping#2]
[Sen1Floods11](https://github.com/cloudtostreet/Sen1Floods11) project provides a training, testing and validation dataset for training Sentinel1 flood inundation model. This issue is to prepare it to be used to train Raster Vision model as baseline for this project.

The images in the dataset are already well tiled, 512x512 GeoTiffs with 256x256 segment layout.

- [x] Copy dataset from google cloud to S3 bucket
- [x] Create STAC metadata for all chips
- [x] The file names are turse, ddd useful descriptions to STAC metadata from the [paper](http://openaccess.thecvf.com/content_CVPRW_2020/html/w11/Bonafilia_Sen1Floods11_A_Georeferenced_Dataset_to_Train_and_Test_Deep_Learning_CVPRW_2020_paper.html)
- [ ] Preserve the split of testing, training, validation sets already present.

The STAC catalog should use [label extension](https://github.com/radiantearth/stac-spec/tree/master/extensions/label) to link water masks with S1 imagery. 

The expected end result are four root catalogs: 
- Full Sen1Floods11 items
- Only Training  items
- Only Testing  items
- Only Validation items

The reason for this split is that it should eventually be possible to train Raster Vision model by pointing it to the training and testing catalogs only.

**Comment by CloudNiner** [comment]
@azavea/operations Part of this task is to transfer ~30GB of data from a public Google Cloud Storage bucket into S3. It appears the Google Cloud `gsutil` command is capable of doing bulk transfers directly to s3 [[1]](https://cloud.google.com/storage/docs/interoperability#using_the_gsutil_command_line) [[2]](https://stackoverflow.com/questions/39329580/exporting-data-from-google-cloud-storage-to-amazon-s3?noredirect=1&lq=1). I'm getting the sense from those links that I'll want to run that from a cloud instance, which I can use an EC2 instance for. Are you aware of a better way to transfer large amounts of data from GCS -> S3?

**Comment by hectcastro** [comment]
I don't think so. I think using `gsutil` from an instance with good network performance, inside of a public subnet (either in GCP or AWS) makes sense.

**Comment by CloudNiner** [comment]
@hectcastro @echeipesh The data in the Google Cloud Storage bucket `gs://cnn_chips` was copied to the S3 bucket `s3://sen1floods11-data` over the weekend via the `gsutil` method described above and I've terminated the instance that did the transfer. 

The `s3://sen1floods11-data` bucket contains an additional `README.md` that states that the bucket is a mirror of the original and provides a few notes on where to look for additional information about the data hosted there.
