### ISSUE TITLE
Reproduce Paper Results

### ISSUE THREAD

**Issue by jamesmcclain** [azavea/noaa-flood-mapping#22]
Data can be found here: https://github.com/cloudtostreet/Sen1Floods11
   - Use data directly from the above source using `geotrellis/deeplab-nlcd` tools
   - Optionally reproduce again using STAC training data produced from the above

**Comment by jamesmcclain** [comment]
### Weakly-Labeled (Sentinel-1) ###

```bash
python3 python/local/sen1floods11_to_tiffs.py --imagery-dir /data/S1_NoQC/ --flood-label-dir /data/S1Flood_NoQC/ --imagery-file /data/weakly-s1-train-imagery.tif --labels-file /data/weakly-s1-train-labels.tif
```

### Weakly-Labeled (Sentinel-2) ###

```bash
python3 python/local/sen1floods11_to_tiffs.py --imagery-dir /data/S1_NoQC/ --flood-label-dir /data/NoQC/ --imagery-file /data/weakly-s2-train-imagery.tif --labels-file /data/weakly-s2-train-labels.tif
```

### Permanent Water ###
```bash
python3 python/local/sen1floods11_to_tiffs.py --imagery-dir /data/S1Perm/ --flood-label-dir /data/PermJRC/ --imagery-file /data/perm-train-imagery.tif --labels-file /data/perm-train-labels.tif --test-set-csv /data/permanent_water_test_data.csv --chip-height 510 --chip-width 510
python3 python/local/sen1floods11_to_tiffs.py --imagery-dir /data/S1Perm/ --flood-label-dir /data/PermJRC/ --imagery-file /data/perm-test-imagery.tif --labels-file /data/perm-test-labels.tif --test-set-csv /data/permanent_water_test_data.csv --chip-height 510 --chip-width 510 --mode test
```

### Hand-Labeled ####
```bash
python3 python/local/sen1floods11_to_tiffs.py --imagery-dir /data/S1/ --flood-label-dir /data/QC_v2/ --perm-label-dir /data/Perm/ --imagery-file /data/hand-train-imagery.tif --labels-file /data/hand-train-labels.tif --test-set-csv /data/flood_test_data.csv
python3 python/local/sen1floods11_to_tiffs.py --imagery-dir /data/S1/ --flood-label-dir /data/QC_v2/ --perm-label-dir /data/Perm/ --imagery-file /data/hand-test-imagery.tif --labels-file /data/hand-test-labels.tif --test-set-csv /data/flood_test_data.csv --mode test
python3 python/local/sen1floods11_to_tiffs.py --imagery-dir /data/S1/ --flood-label-dir /data/QC_v2/ --perm-label-dir /data/Perm/ --imagery-file /data/hand-bolivia-imagery.tif --labels-file /data/hand-bolivia-labels.tif --test-set-csv /data/flood_bolivia_data.csv --mode test
```

**Comment by jamesmcclain** [comment]
| Bolivia           |              Recall |           Precision |                  f1 |       All Water IOU |
|-------------------|---------------------|---------------------|---------------------|---------------------|
| PERMANENT         | 0.44717869926386167 | 0.15381882805255548 | 0.22890111963678422 | 0.12924242806242492 |
| WEAK (SENTINEL-1) |  0.6511334729069584 |   0.610865008421464 |   0.630356787738946 | 0.46023430196710224 |
| WEAK (SENTINEL-2) | 0.33365131356790706 |  0.6797862642686374 |   0.447608387490114 |  0.2883347113467244 |
| HAND-LABELED      |  0.5308215708786385 |  0.6196440537664079 |  0.5718040121492096 |  0.4003680286272787 |

| Hand-Labeled Test |              Recall |           Precision |                 f1 |       All Water IOU |
|-------------------|---------------------|---------------------|--------------------|---------------------|
| PERMANENT         | 0.34246010425776774 | 0.14391046901241777 | 0.2026586184703207 | 0.11275466116394774 |
| WEAK (SENTINEL-1) |  0.7482956320476588 |  0.6984768689249702 | 0.7225285105315511 |   0.565592669964159 |
| WEAK (SENTINEL-2) |  0.5894531165298594 |  0.7712892756431509 | 0.6682218028761295 |   0.501751571184475 |
| HAND-LABELED      |  0.5608633429785019 |  0.7164403952449148 | 0.6291771378995491 | 0.45897770988112135 |

**Comment by echeipesh** [comment]
💯
