### ISSUE TITLE
Study SAR Processing Options

### ISSUE THREAD

**Issue by jamesmcclain** [azavea/noaa-flood-mapping#28]

**Comment by notthatbreezy** [comment]
The one tool mentioned in the kickoff is [pyrosar](https://pyrosar.readthedocs.io/en/latest/index.html) - this is what others use to process SAR data in an ad hoc manner.

I think the concern raised (and I'm by no means a SAR expert so I may have this wrong) is that the Sentinel 1 SAR data in AWS S3 is not orthorectified - it is only georeferenced (Level 1). To orthorectify it requires a DEM. There are some [tools](https://sentinel.esa.int/web/sentinel/toolboxes/sentinel-1) put out by ESA that can process the the level 1 data into level 2 - but they aren't user-friendly. Pyrosar can do this though in what seems a more user-friendly format.

Early on we had been planning on indexing Sentinel 1 data with STAC to find coincidental data, but depending on if we decide the S3 data is useful and needs processing we may not want to do that. One possibility (where we still would build the API) is to create tooling (a la cloud buster) that queries the API to perform some pre-processing step before it hits the AI workflow.
