### ISSUE TITLE
Process SAR data

### ISSUE THREAD

**Issue by jcahail** [azavea/noaa-flood-mapping#35]
In order for the SAR to be most useful for model training as well as prediction, a number of steps should be applied to the Level 1 GRD product, such as radiometric calibration and terrain correction. Azavea will integrate running algorithms provided by the ​Sentinel-1 Toolbox from ESA​ to process the SAR data for inclusion into the training data. This will be done in a way that will allow the steps to also be run on SAR data for inference, as any model trained on processed SAR will require the same type of processing in order to make effective predictions.

**Comment by echeipesh** [comment]
Our advisors indicated that Sentinel-1 Toolbox from ESA may be the painful way to go about this task and suggested we explore pyroSAR for this purpose: https://github.com/azavea/noaa-flood-mapping/issues/39

**Comment by echeipesh** [comment]
We won't do that. For the moment using Sentinel Hub is more economical option that is tracked here: https://github.com/azavea/noaa-flood-mapping/issues/56
Closing this issue until that changes.
