### ISSUE TITLE
Ensure labels are appropriate for Torch models

### ISSUE THREAD

**Issue by moradology** [azavea/noaa-flood-mapping#43]
Data ingests will need to be made palatable for torch learning. At the moment, the Sen1Floods11 dataset that we've ingested and indexed with STAC includes negative labels which result in this error message: ```RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.```

**Comment by jamesmcclain** [comment]
There might be some useful particles [here](https://github.com/geotrellis/deeplab-nlcd/blob/master/python/local/sen1floods11_to_tiffs.py).

**Comment by echeipesh** [comment]
It doesn't look like we can expect the upstream labels to change soon. I would say that the dataset is small enough that its totally fine to just download the affected files, do a `gdal_calc` or python script linked above and upload them. I would suggest to use new dataset name like `S2_NoQA_rev1` so we don't lose track of our modifications when upstream does change.

**Comment by CloudNiner** [comment]
I was able to do this for the hand labeled chips in `QC_v2` via the following steps:

Download the files with:
```
aws s3 cp --recursive --quiet s3://sen1floods11-data/QC_v2 ./QC_v2/
```
Create output directory:
```
mkdir QC_v2_rev1
```

Activate some conda env, install gdal to it with `conda install -c conda-forge gdal`

Create the following script as `./add_one.sh`:
```
#!/bin/bash
for filename in ./QC_v2/*.tif; do
    gdal_calc.py --calc=A+1 --outfile="./QC_v2_rev1/$(basename $filename)" -A "$filename"
done
```

When the script is done, upload the files:
```
aws s3 cp --quiet --recursive ./QC_v2_rev1/ s3://sen1floods11-data/QC_v2_rev1
```

**Comment by CloudNiner** [comment]
The statistics on the new and old files are exactly the same, just shifted up by one int. The tifs are still 512x512 int16 tifs. The magic is in the gdal_calc.py argument `--calc=A+1`.

**Comment by CloudNiner** [comment]
@moradology @echeipesh before I blow through all my bandwidth and CPU cycles and S3 upload/download costs, which other label directories [listed here](https://github.com/cloudtostreet/Sen1Floods11/tree/master/docs) need to be converted for your immediate purposes?
