### ISSUE TITLE
Add Batch Job Definitions to AWS Environment for Franklin Import

### ISSUE THREAD

**Issue by notthatbreezy** [azavea/noaa-flood-mapping#45]
This job definition should parameterize access to the database and other import options using terraform. The command to run will be `import-items`.

This command should take two parameters supplied during job submission:
 - `collectionId`: ID of the collection to import into
 - `collectionItemListFile`: URI to a text file with URIs to stac items to import that are newline separated

**Comment by hectcastro** [comment]
Per the decision on today's call, can this issue be closed?

**Comment by notthatbreezy** [comment]
I opened https://github.com/azavea/noaa-flood-mapping/pull/89 which should close this - it's what I was using to run the batch jobs
