### ISSUE TITLE
Add STACs to NOAA Franklin Instance

### ISSUE THREAD

**Issue by notthatbreezy** [azavea/noaa-flood-mapping#46]
There will be some tracking down of these STACs on S3, but I think all of them have been created

- [ ] [HAND](https://github.com/azavea/noaa-flood-mapping/pull/27)
- [ ] [USFIMR](https://github.com/azavea/noaa-flood-mapping/pull/37)
- [ ] [Sen1Floods11](https://github.com/azavea/noaa-flood-mapping/pull/21)

**Comment by CloudNiner** [comment]
Sen1Floods11 STAC is available at `s3://sen1floods11-data/catalog/catalog.json`. Or, a "self contained" version can be downloaded from `s3://sen1floods11-data/stac-catalog.zip`.

**Comment by jcahail** [comment]
@echeipesh Is this necessary, or nice to have?
