### ISSUE TITLE
USFIMR, S1 ml-aoi catalog

### ISSUE THREAD

**Issue by echeipesh** [azavea/noaa-flood-mapping#57]
Create ml-aoi STAC catalog that will represent the setup for model training

USFIMR has 48 flood events. We need to choose some subset as test and validation.
We can either choose entire flood events or some geographic subset of events.
This decision will likely require manual inspection of events to determine what is and is not representative 
/cc @jamesmcclain -- your call on the strategy on this one

Feature: 
* https://github.com/azavea/noaa-flood-mapping/issues/56
* https://github.com/azavea/noaa-flood-mapping/issues/3

Label: 
* https://github.com/azavea/noaa-flood-mapping/issues/9

Output:
* ml-aoi catalog with S1 feature and USFIMR labels
* ml-aoi catalog with S1, HAND features and USFIMR labels

Note:
This should be a chance to use stac-packer to generate the catalog with minimum fuss.

**Comment by echeipesh** [comment]
@lewfish this is first concrete instance where we need to train Raster Vision model on features that are spread among two input rasters. We could pre-process them into single multi-band raster. I think our last conversation settled on this being a good raster vision feature.

**Comment by lewfish** [comment]
> @lewfish this is first concrete instance where we need to train Raster Vision model on features that are spread among two input rasters. We could pre-process them into single multi-band raster. I think our last conversation settled on this being a good raster vision feature.

I'm leaning against adding lots of data pre-processing features to RV, but this one seems easy to implement, and won't add much to the run-time so I'm OK with adding it. Perhaps the best way to add it would be as a `ConcatRasterSource` that would just concatenate a list of raster sources. It would take a dictionary or something that would specify how to map the bands of the individual raster sources to the joint one.

**Comment by CloudNiner** [comment]
@echeipesh @jamesmcclain working on this now -- looking for input on how to split these events into train, test, validation catalogs.

Here are the s1 chip counts for each USFIMR flood:
```
Imagery coextensive with GLOFIMR flood 1: 29 chips
Imagery coextensive with GLOFIMR flood 2: 16 chips
Imagery coextensive with GLOFIMR flood 3: 25 chips
Imagery coextensive with GLOFIMR flood 15: 7 chips
Imagery coextensive with GLOFIMR flood 16: 22 chips
```

**Comment by lewfish** [comment]
I should have mentioned this before, but the support for combining multiple raster sources in RV was added in https://github.com/azavea/raster-vision/pull/978
