### ISSUE TITLE
Re-train Sen1Floods11 with all USA as the holdout

### ISSUE THREAD

**Issue by CloudNiner** [azavea/noaa-flood-mapping#73]

**Comment by jamesmcclain** [comment]
Just to make things a tiny bit easier, I would suggest holding out Bolivia as a test set, as well.  This will give us one common test that we can use to compare models produced from the original sen1floods11 split and models produced from this split.

**Comment by CloudNiner** [comment]
@jamesmcclain noted, I can do that. 

I was able to get an `inference` RV pipeline to run in Batch and I'm ready to run it again for real with US and Bolivia withheld. Where should I put the output of this task?

**Comment by CloudNiner** [comment]
Also, @jamesmcclain, for consistency with the prior runs, what should I set the `hours` parameter to in the rv_stac_config.py?

**Comment by jamesmcclain** [comment]
> @jamesmcclain noted, I can do that.
> 
> I was able to get an `inference` RV pipeline to run in Batch and I'm ready to run it again for real with US and Bolivia withheld. Where should I put the output of this task?

I don't have a strong opinion, I think that the us-east-1 data bucket is okay with me.

**Comment by jamesmcclain** [comment]
> Also, @jamesmcclain, for consistency with the prior runs, what should I set the `hours` parameter to in the rv_stac_config.py?

I used `4`, but you should expect that to actually take only about 2.5 hours or so on Batch :+1:

**Comment by CloudNiner** [comment]
> us-east-1 data bucket

We ran this once already right? If so, what's the S3 uri to that existing run?

**Comment by CloudNiner** [comment]
Here are the commands I used to generate these catalogs:
```
python3 build_catalog.py hand \
    --valid-csv ./data/flood_valid_data_not_usa.csv \
    --test-csvs ./data/flood_usa_data.csv \
    --test-csvs ./data/flood_bolivia_data.csv
python3 build_catalog.py s1weak \
    --valid-csv ./data/flood_valid_data_not_usa.csv \
    --test-csvs ./data/flood_usa_data.csv \
    --test-csvs ./data/flood_bolivia_data.csv
python3 build_catalog.py s2weak \
    --valid-csv ./data/flood_valid_data_not_usa.csv \
    --test-csvs ./data/flood_usa_data.csv \
    --test-csvs ./data/flood_bolivia_data.csv
```

And here's a zip containing those three csv files: [usa_experiment_csvs.zip](https://github.com/azavea/noaa-flood-mapping/files/5198059/usa_experiment_csvs.zip)

@jamesmcclain could you double check these csvs to ensure that I've understood our discussion correctly?

**Comment by jamesmcclain** [comment]
> @jamesmcclain could you double check these csvs to ensure that I've understood our discussion correctly?

Yes, the contents of the CSVs appears to be consistent with the discussion above :+1:

**Comment by CloudNiner** [comment]
This effort is complete. All three experiments, `hand`, `s1weak` and `s2weak` were re-run and the results are available at:

`s3://noaafloodmap-data-us-east-1/experiments/sen1floods11/withhold-usa/20200910-001/`

That directory also contains a README that includes the commands run to reproduce the experiment, copies of the csvs used to generate the mldata catalog, and the zipped mldata catalog.
