### ISSUE TITLE
Copernicus EMSR Flood Events

### ISSUE THREAD

**Issue by echeipesh** [azavea/noaa-flood-mapping#85]
This issue is to create a catalogue for Copernicus EMSR flood activation.
Source: https://emergency.copernicus.eu/mapping/list-of-activations-rapid

We would like to create additional training data for the flood model. That requires:
* time and AOI of a flood event
* Sentinel-2 scene to generate training labels by application of water detection model
* Sentinel-1 scene for feature input

This issue is to take care of first requirement. We want a catalogue of flood events from 2019-01-01 to present.
The ideal output is something that reassembles the USFIMR catalogue we have crated.
Reviewing the UMSR flood events there are three pieces of data we care about:

- date and time (appears to be only in HTML body)
- AOI is one of the shape files in the downloadable "Vector Package" zip
- `observedEvent` feature in shape files

Desired output should be
- Each item should have `EMSR####` activation ID as its ID
- Each item should have the event temporal bounds as its metadata
- Each item should have the event AOI as its geometry
- Each tiem should have `observedEvent` asset as WKT and GeoJSON (match USFIMR STAC)

We're probably not going to use `observedEvent` geometry for training but almost certainly we'll want to have easy access to it for validation and sanity checking as we do processing.

**Comment by CloudNiner** [comment]
Each Copernicus flood event has:
- 1 or more distinct Areas of Interest that flood extents are computed for
- 1 or more "monitoring" passes after the event for the [Delineation and Grading products](https://emergency.copernicus.eu/mapping/ems/rapid-mapping-portfolio)
- 1 or more [revisions](https://emergency.copernicus.eu/mapping/ems/release-product)
- 1 or more [versions](https://emergency.copernicus.eu/mapping/ems/version-product)

There is a GeoRSS feed for the events and a GeoRSS feed for available products for each individual event, but there is no way to construct an automated download link for the VECTOR data zip files we need to get the detected flood geometries for a specific combination of AOI, product, revision, version. So, we need to manually download a large quantity of data and determine which of these combinations are appropriate for our use case.

But...before we do all that we want event AOIs that intersect with public sentinel 2 data from SentinelHub. To do that, we need event AOI polygons and event times, which _are_ available in the GeoRSS. 

So, after a discussion about all this with @echeipesh, this task is now scoped to parsing the GeoRSS feeds, and querying sentinel hub to find which flood events+aoi+products intersect with said sentinel 2 scenes. From there we can prepare further work based on the quantity and quality of the intersections.
