### ISSUE TITLE
GloFIMR STAC

### ISSUE THREAD

**Issue by echeipesh** [azavea/noaa-flood-mapping#9]
This issue is to create STAC item metadata for [USFIMR](https://sdml.ua.edu/usfimr/) flood extents.
This is meant to enable indexing this dataset with Franklin to enable easier searching

- [x] Generate STAC
- [x] Consider transforming shape files into GeoJSON

The source shapefiles are only published in zipped format on HTTP endpoints. This probably still allows them to be accessible through GDAL/OGR. However, its not clear if we will need to unzip and/or encode them as GeoJSON for better accessibility in this project. Discussing and investigating that is part of this issue.

**Comment by moradology** [comment]
Looks like the best practices have something to say about storing vector layers: https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#representing-vector-layers-in-stac
